# Generated by Django 2.1.2 on 2018-11-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(default='link', max_length=500),
            preserve_default=False,
        ),
    ]
