# Generated by Django 2.1.2 on 2018-11-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alt',
            field=models.CharField(default='hello world text', max_length=100),
            preserve_default=False,
        ),
    ]
